services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://ashraf3:reeha@cluster0.urj35.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    disk:
      name: fastapi-disk
      mountPath: /var/lib/data
      sizeGB: 1
